### ISSUE TITLE
Question: gl.getAttribLocation undefined behavior

### ISSUE THREAD

**Issue by maurizzzio** [stackgl/gl-shader#7]
I saw that `gl-shader` sets an increasing number for the location of each attribute done after the attributes have been sorted lexicographically, the source mentions that there's an [undefined WebGL behavior regarding the location of an attribute](https://github.com/stackgl/gl-shader/blob/master/index.js#L113-L114), if a custom attribute location behavior is defined on `gl-shader` may I ask what is the problem with `gl.getAttribLocation`?

**Comment by mikolalysenko** [comment]
Because it is non-determinisitic, it can cause bugs.

For example, attribute 0 is weird and you can't set it using gl.vertexAttrib4f(...) for example without breaking some webgl implementations or suffering performance problems.  If you are using vertexAttrib and you compile on an implementation that shuffles the order of attributes around it could break your shader code.

Other problems can occur if you are using the same vertex state across multiple draw calls (for example, one pass for forward, one for shadows, etc.)  In this case you might run into bugs when you try to reproduce your code across different systems if the shaders shuffle the attributes around.

By fixing the attribute order, you get deterministic behavior so you can reliably reproduce problems if they occur.

**Comment by maurizzzio** [comment]
Thanks for the clear and detailed explanation :)
